public enum EventID
{
    EarnGold,
    EatFood,
    EnemyDie,
    PlayerDie,
    WasEat,
    LevelUp,
    EatItem,
    RespawnEnemy,
    ShieldHit,
    EarnMoney,
    SpendMoney,
    BlockSide,
    MovingAgain,
    RemoveEnemyTransform,

    // Settings
    OnSoundChange,
    OnMusicChange,
    OnVibrationChange,

    //UI
    DailyCheckInClaimReward,
    EnemyKill,
    StatUpgradeSuccess,
    SkinElementSelect,
    SkinUsingSelected,
    SkinUnlockSuccess,
    SkinRandomSuccess,
    StatUpgradeSuccessFree,
    ReviveSuccess,
    EnemyAttack,
    PlayerUpLevel,
    PlayerUpScore,
    WasHitBulelt ,
    EnemyWasHitBullet,
    GameOver,
    AddHP,
    SkipBg,
    WaveEnd,
    UpdateCoins,
    Victory,
    SelectLevel,
    CountEnemy,
    OutOffEnemy,
    ExitGame,
    PlayerUpEXP,
}